import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { LinkButton } from "~/component/LinkButton";

function HeroBanner() {
  return (
    <section className="mb-24 mt-12 grid grid-cols-1 gap-12 px-8 sm:mt-24 sm:grid-cols-2">
      <div className="flex flex-col gap-4">
        <h1 className="text-6xl">
          Generate an beautiful images with your favorite songs
        </h1>
        <p className="text-2xl">
          Use AI to help sculpt each image to express the emotion of each song
        </p>
        <LinkButton href="generate" className="self-start">
          Generate Images
        </LinkButton>
      </div>
      <Image
        src="/yellow-ai.png"
        alt="banner image"
        width="400"
        height="300"
        className="order-first sm:order-none"
      />
    </section>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Feels Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
};

export default Home;
