/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

const TestEffectPage: NextPage = () => {
  const [mount, setMount] = useState(false);
  // const elementRef = useRef<HTMLParagraphElement | null>(null);
  const enhance = (id: string) => {
    if (!id) return;
    const element: HTMLElement | null = document.getElementById(id);
    const text: string[] | null = element?.innerText.split("") || null;
    if (element) {
      element.innerText = "";
      if (text) {
        text.forEach((letter) => {
          const span = document.createElement("span");
          span.className = "letter";
          span.innerText = letter;
          element?.appendChild(span);
        });
      }
    }
  };

  useEffect(() => {
    if (!mount) {
      enhance("channel-link");
      setMount(true);
    }
  }, [mount]);

  return (
    <>
      <Head>
        <title>Generate an Image that makes you feel</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <main>
        <div className="px-20">
          <div id="text" className="">
            <div className="line">
              <p className="word">Imagine</p>
              <p className="word alt">Create</p>
            </div>
            <div className="line">
              <p className="word">Mind-Bending</p>
              <p className="word alt">Feel</p>
            </div>
            <div className="line">
              {/* <p className="word fancy">@Jmachentash</p> */}
              <p id="channel-link" className="word fancy">
                @Jmachentash
              </p>
            </div>
            <div className="line">
              <p className="word fancy">Generate</p>
            </div>
          </div>
        </div>

        {/* <Banner /> */}
      </main>
      {/* <main> */}
      {/* </main> */}
    </>
  );
};

export default TestEffectPage;
